-- ════════════════════════════════════════════
-- THE SMART GOLFER — Calendrier des tournois + Messagerie (S22/S23)
-- À coller dans : Supabase → SQL Editor → New query → Run
-- Idempotent. Nécessite schema.sql + coach_hub.sql + groups.sql.
-- ════════════════════════════════════════════

-- ═════════ 1) CALENDRIER / TOURNOIS ═════════
create table if not exists public.events (
  id         uuid primary key default gen_random_uuid(),
  title      text not null,
  event_date date,
  course     text,
  notes      text,
  scope      text not null check (scope in ('coach','group')),
  scope_id   uuid not null,   -- coach_id (=created_by) pour 'coach' ; group_id pour 'group'
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz default now()
);
alter table public.events enable row level security;
create index if not exists events_scope_idx on public.events(scope, scope_id);

-- Peut-on voir cet événement ? (SECURITY DEFINER : évite la récursion RLS)
create or replace function public.can_see_event(eid uuid)
returns boolean language sql security definer stable set search_path = public as $$
  select exists (
    select 1 from public.events e where e.id = eid and (
      e.created_by = auth.uid()
      or (e.scope = 'group' and public.is_group_member(e.scope_id))
      or (e.scope = 'coach' and exists (
            select 1 from public.coach_players cp
            where cp.coach_id = e.scope_id and cp.player_id = auth.uid()))
    )
  );
$$;
grant execute on function public.can_see_event(uuid) to authenticated;

drop policy if exists "events_select" on public.events;
create policy "events_select" on public.events for select using (public.can_see_event(id));

drop policy if exists "events_insert" on public.events;
create policy "events_insert" on public.events for insert with check (
  created_by = auth.uid() and (
    (scope = 'group' and public.is_group_member(scope_id))
    or (scope = 'coach' and scope_id = auth.uid())
  )
);

drop policy if exists "events_update" on public.events;
create policy "events_update" on public.events for update using (created_by = auth.uid());

drop policy if exists "events_delete" on public.events;
create policy "events_delete" on public.events for delete using (created_by = auth.uid());

-- Participation aux tournois
create table if not exists public.event_participants (
  event_id   uuid not null references public.events(id) on delete cascade,
  user_id    uuid not null references auth.users(id) on delete cascade,
  status     text not null default 'in' check (status in ('in','out','maybe')),
  updated_at timestamptz default now(),
  primary key (event_id, user_id)
);
alter table public.event_participants enable row level security;

drop policy if exists "ep_select" on public.event_participants;
create policy "ep_select" on public.event_participants for select using (public.can_see_event(event_id));

drop policy if exists "ep_write" on public.event_participants;
create policy "ep_write" on public.event_participants for all
  using (user_id = auth.uid())
  with check (user_id = auth.uid() and public.can_see_event(event_id));

-- ═════════ 2) MESSAGERIE ═════════
create table if not exists public.messages (
  id           bigint generated by default as identity primary key,
  channel_type text not null check (channel_type in ('coach','group')),
  group_id     uuid,
  coach_id     uuid,
  player_id    uuid,
  sender_id    uuid not null references auth.users(id) on delete cascade,
  body         text not null,
  created_at   timestamptz default now()
);
alter table public.messages enable row level security;
create index if not exists messages_group_idx on public.messages(group_id, created_at);
create index if not exists messages_coach_idx on public.messages(coach_id, player_id, created_at);

drop policy if exists "messages_select" on public.messages;
create policy "messages_select" on public.messages for select using (
  (channel_type = 'group' and public.is_group_member(group_id))
  or (channel_type = 'coach' and (auth.uid() = coach_id or auth.uid() = player_id))
);

drop policy if exists "messages_insert" on public.messages;
create policy "messages_insert" on public.messages for insert with check (
  sender_id = auth.uid() and (
    (channel_type = 'group' and public.is_group_member(group_id))
    or (channel_type = 'coach' and (auth.uid() = coach_id or auth.uid() = player_id))
  )
);

-- ════════════════════════════════════════════
-- FIN
-- ════════════════════════════════════════════
