-- ════════════════════════════════════════════
-- THE SMART GOLFER — Mise à jour « week-end de test » (S55 et suivantes)
-- À coller EN ENTIER dans : Supabase → SQL Editor → New query → Run
-- Idempotent (on peut le relancer sans risque).
-- L'app fonctionne AVANT son exécution (les avis sont gardés et renvoyés).
-- ════════════════════════════════════════════

-- ─────────────────────────────────────────────
-- S55 — « Ton avis » : retours des testeurs
-- Tout le monde peut ENVOYER un avis (même en mode démo) ; personne ne peut
-- les LIRE depuis l'app. Toi, tu les lis dans Supabase :
--   Table Editor → feedback   (ou la requête en bas de ce bloc)
create table if not exists public.feedback (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  user_id     uuid references auth.users(id) on delete set null,
  mood        smallint check (mood between 1 and 5),
  category    text check (category is null or char_length(category) <= 20),
  body        text check (body is null or char_length(body) <= 2000),
  page        text check (page is null or char_length(page) <= 30),
  meta        jsonb
);
alter table public.feedback enable row level security;

drop policy if exists "feedback_insert" on public.feedback;
create policy "feedback_insert" on public.feedback
  for insert to anon, authenticated
  with check (user_id is null or user_id = auth.uid());

-- Pour lire les avis (à lancer quand tu veux) :
--   select created_at, mood, category, body, page, meta->>'rounds' as parties
--   from public.feedback order by created_at desc;
