-- ════════════════════════════════════════════
-- THE SMART GOLFER — Schéma Supabase (Étape 2)
-- À coller dans : Supabase → SQL Editor → New query → Run
-- Idempotent : peut être relancé sans casser l'existant.
-- ════════════════════════════════════════════

-- ─────────────────────────────────────────────
-- 1) PROFILS (extension de auth.users)
-- ─────────────────────────────────────────────
create table if not exists public.profiles (
  id         uuid primary key references auth.users(id) on delete cascade,
  name       text,
  hcp        numeric,
  role       text default 'player',       -- player | captain | coach | head
  color      text,
  bg         text,
  initials   text,
  created_at timestamptz default now()
);

alter table public.profiles enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles
  for select using (auth.uid() = id);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own" on public.profiles
  for insert with check (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles
  for update using (auth.uid() = id);

-- Création automatique d'un profil à l'inscription
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, name, hcp, role, color, bg, initials)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    nullif(new.raw_user_meta_data->>'hcp', '')::numeric,
    coalesce(new.raw_user_meta_data->>'role', 'player'),
    coalesce(new.raw_user_meta_data->>'color', '#C9A84C'),
    coalesce(new.raw_user_meta_data->>'bg', 'rgba(201,168,76,0.2)'),
    coalesce(new.raw_user_meta_data->>'initials', upper(left(coalesce(new.raw_user_meta_data->>'name', new.email), 2)))
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ─────────────────────────────────────────────
-- 2) PARTIES (rounds)
-- ─────────────────────────────────────────────
create table if not exists public.rounds (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users(id) on delete cascade,
  played_on   date,
  course      text,
  course_id   text,
  score       integer,
  par         integer,
  diff        numeric,
  fir         integer,
  fir_total   integer,
  gir         integer,
  putts       integer,
  cond        text,
  format      text,
  hcp         numeric,
  notes       text,
  scores      jsonb,
  sg_tee      numeric,
  sg_app      numeric,
  sg_arg      numeric,
  sg_putt     numeric,
  created_at  timestamptz default now()
);

alter table public.rounds enable row level security;
create index if not exists rounds_user_idx on public.rounds(user_id);

drop policy if exists "rounds_all_own" on public.rounds;
create policy "rounds_all_own" on public.rounds
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ─────────────────────────────────────────────
-- 3) OBJECTIFS DE SAISON (1 ligne par utilisateur)
-- ─────────────────────────────────────────────
create table if not exists public.objectives (
  user_id    uuid primary key references auth.users(id) on delete cascade,
  score      numeric,
  hcp        numeric,
  gir        numeric,
  fir        numeric,
  putts      numeric,
  updated_at timestamptz default now()
);

alter table public.objectives enable row level security;

drop policy if exists "objectives_all_own" on public.objectives;
create policy "objectives_all_own" on public.objectives
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ─────────────────────────────────────────────
-- 4) PARCOURS UTILISATEUR
-- ─────────────────────────────────────────────
create table if not exists public.user_courses (
  id         text primary key,             -- ex. 'user-<timestamp>'
  user_id    uuid not null references auth.users(id) on delete cascade,
  data       jsonb not null,               -- l'objet parcours complet (18 trous, etc.)
  created_at timestamptz default now()
);

alter table public.user_courses enable row level security;
create index if not exists user_courses_user_idx on public.user_courses(user_id);

drop policy if exists "user_courses_all_own" on public.user_courses;
create policy "user_courses_all_own" on public.user_courses
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ─────────────────────────────────────────────
-- 5) EXERCICES / ENTRAÎNEMENTS
--    Créés par les coachs, lisibles par tous les utilisateurs connectés.
-- ─────────────────────────────────────────────
create table if not exists public.trainings (
  id          text primary key,            -- ex. 'trn-<timestamp>'
  created_by  uuid not null references auth.users(id) on delete cascade,
  author_name text,
  type        text,                        -- exercice | entrainement
  title       text not null,
  category    text,
  level       text,
  duration    integer,
  objective   text,
  description text,
  created_at  timestamptz default now()
);

alter table public.trainings enable row level security;
create index if not exists trainings_author_idx on public.trainings(created_by);

-- Lecture : tout utilisateur connecté (les joueurs voient les exercices des coachs)
drop policy if exists "trainings_select_auth" on public.trainings;
create policy "trainings_select_auth" on public.trainings
  for select using (auth.role() = 'authenticated');

-- Écriture : uniquement l'auteur
drop policy if exists "trainings_write_own" on public.trainings;
create policy "trainings_write_own" on public.trainings
  for all using (auth.uid() = created_by) with check (auth.uid() = created_by);

-- ─────────────────────────────────────────────
-- 6) RÉALISATIONS D'EXERCICES (par joueur)
-- ─────────────────────────────────────────────
create table if not exists public.training_done (
  user_id     uuid not null references auth.users(id) on delete cascade,
  training_id text not null,
  count       integer default 0,
  last_done   timestamptz,
  primary key (user_id, training_id)
);

alter table public.training_done enable row level security;

drop policy if exists "training_done_all_own" on public.training_done;
create policy "training_done_all_own" on public.training_done
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ════════════════════════════════════════════
-- FIN — les groupes (#5) auront leur propre script plus tard.
-- ════════════════════════════════════════════
